title:            Vittorio Caggiano
locale:           en_US
description: > # this means to ignore newlines until "baseurl:"

permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://caggiano.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Vittorio Caggiano # add your name
author-img: vittorio_caggiano.jpg # add your photo
about-author: I am a TPM and researcher in motor control and AI at Meta in NYC.
social-twitter: CaggianoVitt # add your Twitter handle
social-facebook: vittorio.caggiano.7 # add your Facebook handle
social-github: Vittorio-Caggiano # add your Github handle
social-linkedin: vittorio-caggiano-26b6a7b # add your Linkedin handle
social-email: caggiano@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
